import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./theme-config.css"
import NavBar from "./component/NavBar";
import '@radix-ui/themes/styles.css';
import { Theme, ThemePanel } from "@radix-ui/themes";
import { Toaster } from "sonner";
import Authentication from "./auth/provider";

const inter = Inter(
  { subsets: ["latin"],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className} >
        <Authentication>
      <Theme accentColor="violet" radius="large" scaling="105%">
        <NavBar/>
        <main>{children}</main>
        <Toaster position="bottom-right"/>
        <Toaster richColors  />
        </Theme>
        </Authentication>
        </body>
        
    </html>
  );
}
